version: '3.7'

services:
  php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    image: slim_php
    container_name: slim_php
    env_file:
      - ./.env
    ports:
      - '80:80'
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
    links:
      - mysql
    networks:
      slim-net:
        ipv4_address: 192.168.40.3

  mysql:
    image: mysql:5.6
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    env_file: ./.env
    ports:
      - '3306:3306'
    volumes:
      - ${DB_DATA_PATH}:/var/lib/mysql
    networks:
      slim-net:
        ipv4_address: 192.168.40.2

networks:
  slim-net:
    external: true
